/**
 * @copyright ecyht2 2023
 * @file A leaflet path using markers as points.
 * @module path-list
 * */

"use strict"

/** @alias Coordinates number[]
 * */

/**
 * A path generated by markers.
 * */
export default class PathList {
  /**
   * Next marker in the path.
   *
   * @type {PathList}
   * */
  $next = null;
  /**
   * Previous marker in the path.
   *
   * @type {PathList}
   * */
  $prev = null;
  $coords = null;

  /**
   * Constructs a PathList.
   *
   * @param coords {Coordinates} The initial coordinate of the path.
   * @param parent {PathList} The initial coordinate of the path.
   * */
  constructor(coords, parent = null) {
    this.$coords = coords;
    this.$prev = parent;
  }

  /**
   * Adds a new point in the path.
   *
   * @param coords {Coordinates} The coordinate of the new point.
   * */
  push(coords) {
    let current = this;
    while (current.$next !== null) {
      current = this.$next;
    }

    current.$next = new PathList(coords, current);
  }

  /**
   *
   * @param map {L.Map} The map.
   * */
  draw(map) {
  }
}
